ifeq ($(CONFIG_OF),y)

ifneq ($(CONFIG_MMI_DEVICE_DTBS),y)
dtb-$(CONFIG_ARCH_MSM8974) += msm8974-v1-cdp.dtb \
	msm8974-v1-fluid.dtb \
	msm8974-v1-liquid.dtb \
	msm8974-v1-mtp.dtb \
	msm8974-v1-rumi.dtb \
	msm8974-v1-sim.dtb \
	msm8974-v2.0-1-cdp.dtb \
	msm8974-v2.0-1-fluid.dtb \
	msm8974-v2.0-1-liquid.dtb \
	msm8974-v2.0-1-mtp.dtb \
	apq8074-v2.0-1-cdp.dtb \
	apq8074-v2.0-1-liquid.dtb \
	apq8074-v2.0-1-dragonboard.dtb \
	apq8074-v2.2-cdp.dtb \
	apq8074-v2.2-liquid.dtb \
	apq8074-v2.2-dragonboard.dtb \
	msm8974-v2.2-cdp.dtb \
	msm8974-v2.2-fluid.dtb \
	msm8974-v2.2-liquid.dtb \
	msm8974-v2.2-mtp.dtb \
	msm8974pro-ab-pm8941-cdp.dtb \
	msm8974pro-ab-pm8941-fluid.dtb \
	msm8974pro-ab-pm8941-liquid.dtb \
	msm8974pro-ab-pm8941-mtp.dtb \
	msm8974pro-ac-pm8941-cdp.dtb \
	msm8974pro-ac-pm8941-liquid.dtb \
	msm8974pro-ac-pm8941-mtp.dtb \
	msm8974pro-ac-pma8084-pm8941-mtp.dtb
dtb-$(CONFIG_ARCH_MSM8916) += msm8916-sim.dtb \
	msm8916-rumi.dtb
dtb-$(CONFIG_ARCH_MSM8226) += msm8226-sim.dtb \
	msm8226-fluid.dtb \
	msm8226-v1-cdp.dtb \
	msm8226-v1-mtp.dtb \
	msm8226-v1-qrd-evt.dtb \
	msm8226-v1-qrd-dvt.dtb \
	msm8226-v2-720p-cdp.dtb \
	msm8226-v2-1080p-cdp.dtb \
	msm8226-v2-720p-mtp.dtb \
	msm8226-v2-1080p-mtp.dtb \
	msm8226-v2-qrd-evt.dtb \
	msm8226-v2-qrd-dvt.dtb \
	msm8926-v1-720p-cdp.dtb \
	msm8926-v1-1080p-cdp.dtb \
	msm8926-v1-720p-mtp.dtb \
	msm8926-v1-1080p-mtp.dtb \
	msm8926-v1-qrd.dtb \
	msm8926-v1-qrd-skug.dtb \
	msm8926-v1-qrd-skug-pvt.dtb \
	msm8926-v2-720p-cdp.dtb \
	msm8926-v2-1080p-cdp.dtb \
	msm8926-v2-1080p-ext-buck-cdp.dtb \
	msm8926-v2-720p-mtp.dtb \
	msm8926-v2-1080p-mtp.dtb \
	msm8926-v2-1080p-ext-buck-mtp.dtb \
	msm8926-v2-qrd.dtb \
	msm8926-v2-qrd-skug.dtb \
	msm8926-v2-qrd-skug-pvt.dtb \
	msm8226-v1-qrd-skuf.dtb \
	msm8226-v2-qrd-skuf.dtb \
	apq8026-v1-xpm.dtb \
	apq8026-v1-cdp.dtb \
	apq8026-v1-mtp.dtb \
	apq8026-v2-xpm.dtb \
	apq8026-v2-720p-cdp.dtb \
	apq8026-v2-1080p-cdp.dtb \
	apq8026-v2-720p-mtp.dtb \
	apq8026-v2-1080p-mtp.dtb
dtb-$(CONFIG_ARCH_MSM8610) += msm8610-rumi.dtb \
	msm8610-v1-cdp.dtb \
	msm8610-v2-cdp.dtb \
	msm8610-v1-mtp.dtb \
	msm8610-v2-mtp.dtb \
	msm8610-sim.dtb \
	msm8610-v1-qrd-skuaa.dtb \
	msm8610-v1-qrd-skuab.dtb \
	msm8610-v2-qrd-skuaa.dtb \
	msm8610-v2-qrd-skuab.dtb
dtb-$(CONFIG_ARCH_FSM9900) += fsm9900-rumi.dtb \
	fsm9900-sim.dtb \
	fsm9900-cdp.dtb \
	fsm9900-mtp.dtb
dtb-$(CONFIG_ARCH_MDM9630) += mdm9630-sim.dtb \
	mdm9630-cdp.dtb \
	mdm9630-mtp.dtb
dtb-$(CONFIG_ARCH_MSMSAMARIUM) += msmsamarium-sim.dtb \
	msmsamarium-rumi.dtb \
	msmsamarium-cdp-interposer.dtb \
	msmsamarium-cdp.dtb \
	msmsamarium-mtp.dtb \
	apqsamarium-mtp.dtb
dtb-$(CONFIG_ARCH_MPQ8092) += mpq8092-sim.dtb \
	mpq8092-rumi.dtb \
	mpq8092-cdp.dtb \
	mpq8092-dtv.dtb \
	mpq8092-dma.dtb
dtb-$(CONFIG_ARCH_APQ8084) += apq8084-v1.0-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-liquid.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x25-cdp.dtb \
	apq8084-v1.1-smb1357-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-smb1357-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-old-pwr-grid-smb349-cdp.dtb \
	apq8084-old-pwr-grid-smb349-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-sbc.dtb
dtb-$(CONFIG_ARCH_MSM) += msmplutonium-sim.dtb

else # CONFIG_MMI_DEVICE_DTBS

# MSM8974 Motorola Devices
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ab-victara-p0.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ab-victara-p1b.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ab-victara-p2a.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ab-victara-p2b.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara-p1b.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara-p2a.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara-p2b.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara-p2bf.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara_cn-p1a.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-victara_cn-p3.dtb
dtb-$(CONFIG_ARCH_MSM8974)	+= msm8974pro-ac-orthos-p1.dtb

# MSM8226 Motorola Devices
ifeq ($(CONFIG_MMI_TITAN_DTB),y)
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-titan-4b.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-titan-4c.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-titan-4d.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-titan-4e.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-titan-4f.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-thea-p1a.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-thea-p1c.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-thea-p2.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-thea-p3.dtb
else ifeq ($(CONFIG_MMI_PEREGRINE_DTB),y)
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-peregrine-p1.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-peregrine-p1c.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-peregrine-p2.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-peregrine-p2a1.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8926-peregrine-p2d.dtb
else
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-bigfoot-p1.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p1.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p2.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p2-v2.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p2b.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p2b1.dtb
dtb-$(CONFIG_ARCH_MSM8226)	+= msm8226-falcon-p3c.dtb
endif

# MSM8610 Motorola Devices
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p0.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p0c.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p0c-v2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1b.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1b-v2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1c.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1c-v2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1d.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p1d-v2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p2a1.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p2b.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-condor-p2b1.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-otus-p1.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-otus-p2.dtb
dtb-$(CONFIG_ARCH_MSM8610)	+= msm8610-otus-p2b.dtb

endif # CONFIG_MMI_DEVICE_DTBS

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

targets += dtbs
endif

$(obj)/../%.dtb: $(src)/%.dts
	$(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/../,$(DTB_LIST))

clean-files := *.dtb
